services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Sai@3999
      POSTGRES_DB: fampay
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - freshfeed-network

  backend:
    build: ./backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      - PORT=5000
      - DB_USER=postgres
      - DB_PASS=Sai@3999
      - DB_HOST=postgres
      - DB_NAME=fampay
      - DB_PORT=5432
      - YOUTUBE_API_KEY=AIzaSyAI5oi0p3zHgIMjpEoHxoFrglsJ9hfC734,AIzaSyDkKJNj30XKoPCuqAClK562nCMzMDf3yrA,AIzaSyBy1AYGVRNXejbpOekuqJNUF2s_UPSa9-M
    networks:
      - freshfeed-network

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - freshfeed-network

volumes:
  pgdata:

networks:
  freshfeed-network:
    driver: bridge
